services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    # image: 503240354556.dkr.ecr.us-east-2.amazonaws.com/reservations:latest
    image: us-east4-docker.pkg.dev/sleepr-402417/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: us-east4-docker.pkg.dev/sleepr-402417/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: us-east4-docker.pkg.dev/sleepr-402417/payments/production
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: us-east4-docker.pkg.dev/sleepr-402417/notifications/production
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo